# Generated by Django 4.1.5 on 2023-02-03 09:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_remove_recipe_date_create'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
